In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Customer Segmentation

In [8]:
transactions = pd.read_csv("transactions.csv")
transactions.head()

  transaction_id user_id transaction_date  amount   status
0        T000001  U00001       2025-04-14    1000  success
1        T000002  U00003       2025-04-05    2000  success
2        T000003  U00004       2025-01-18    1000  success
3        T000004  U00008       2025-01-23    1000  success
4        T000005  U00011       2025-03-31    2000  success

In [6]:
user_revenue = transactions.groupby("user_id")["amount"].sum().reset_index()
user_revenue

     user_id  amount
0     U00001    1000
1     U00003    2000
2     U00004    1000
3     U00008    1000
4     U00011    2000
...      ...     ...
2103  U04990    5000
2104  U04991    2000
2105  U04993    1000
2106  U04998    1000
2107  U04999    1000

[2108 rows x 2 columns]

In [7]:
user_revenue["segment"] = pd.qcut(
    user_revenue["amount"],
    q=3,
    labels=["Low Value", "Mid Value", "High Value"]
)

In [9]:
user_revenue.segment.value_counts()

segment
Low Value     1185
High Value     529
Mid Value      394
Name: count, dtype: int64

### Revenue is highly concentrated among a small group of high-value users, indicating an opportunity to prioritize retention and engagement strategies for this segment.